// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file_registry.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmptyFile = `-- name: CreateEmptyFile :one
insert into file_registry (
    user_id,
    file_name,
    lock_status,
    upload_status
) values (
    $1, $2, $3, $4
) returning id, user_id, file_name, object_key, lock_status, upload_status, created_at, updated_at
`

type CreateEmptyFileParams struct {
	UserID       int32  `json:"user_id"`
	FileName     string `json:"file_name"`
	LockStatus   bool   `json:"lock_status"`
	UploadStatus string `json:"upload_status"`
}

func (q *Queries) CreateEmptyFile(ctx context.Context, arg CreateEmptyFileParams) (FileRegistry, error) {
	row := q.db.QueryRow(ctx, createEmptyFile,
		arg.UserID,
		arg.FileName,
		arg.LockStatus,
		arg.UploadStatus,
	)
	var i FileRegistry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.ObjectKey,
		&i.LockStatus,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
delete from file_registry
where id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
select upload_status, lock_status, updated_at
from file_registry
where id = $1
for update
`

type GetFileByIDRow struct {
	UploadStatus string             `json:"upload_status"`
	LockStatus   bool               `json:"lock_status"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFileByID(ctx context.Context, id int32) (GetFileByIDRow, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i GetFileByIDRow
	err := row.Scan(&i.UploadStatus, &i.LockStatus, &i.UpdatedAt)
	return i, err
}

const getFileByName = `-- name: GetFileByName :one
select id, user_id, file_name, object_key, lock_status, upload_status, created_at, updated_at from file_registry
where
    file_name = $1 
    and user_id = $2
for update
`

type GetFileByNameParams struct {
	FileName string `json:"file_name"`
	UserID   int32  `json:"user_id"`
}

func (q *Queries) GetFileByName(ctx context.Context, arg GetFileByNameParams) (FileRegistry, error) {
	row := q.db.QueryRow(ctx, getFileByName, arg.FileName, arg.UserID)
	var i FileRegistry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.ObjectKey,
		&i.LockStatus,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockFile = `-- name: LockFile :one
update file_registry
set
    lock_status = $1,
    updated_at = current_timestamp
where id = $2
returning id, user_id, file_name, object_key, lock_status, upload_status, created_at, updated_at
`

type LockFileParams struct {
	LockStatus bool  `json:"lock_status"`
	ID         int32 `json:"id"`
}

func (q *Queries) LockFile(ctx context.Context, arg LockFileParams) (FileRegistry, error) {
	row := q.db.QueryRow(ctx, lockFile, arg.LockStatus, arg.ID)
	var i FileRegistry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.ObjectKey,
		&i.LockStatus,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileMetadata = `-- name: UpdateFileMetadata :one
update file_registry
set
    object_key = $1,
    upload_status = $2,
    lock_status = $3,
    updated_at = current_timestamp
where id = $4
returning id, user_id, file_name, object_key, lock_status, upload_status, created_at, updated_at
`

type UpdateFileMetadataParams struct {
	ObjectKey    pgtype.Text `json:"object_key"`
	UploadStatus string      `json:"upload_status"`
	LockStatus   bool        `json:"lock_status"`
	ID           int32       `json:"id"`
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (FileRegistry, error) {
	row := q.db.QueryRow(ctx, updateFileMetadata,
		arg.ObjectKey,
		arg.UploadStatus,
		arg.LockStatus,
		arg.ID,
	)
	var i FileRegistry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.ObjectKey,
		&i.LockStatus,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileName = `-- name: UpdateFileName :one
update file_registry
set
    file_name = $1,
    updated_at = current_timestamp
where id = $2
returning id, user_id, file_name, object_key, lock_status, upload_status, created_at, updated_at
`

type UpdateFileNameParams struct {
	NewFileName string `json:"new_file_name"`
	ID          int32  `json:"id"`
}

func (q *Queries) UpdateFileName(ctx context.Context, arg UpdateFileNameParams) (FileRegistry, error) {
	row := q.db.QueryRow(ctx, updateFileName, arg.NewFileName, arg.ID)
	var i FileRegistry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.ObjectKey,
		&i.LockStatus,
		&i.UploadStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
