// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int32              `json:"id"`
	UserID     int32              `json:"user_id"`
	Credential []byte             `json:"credential"`
	Signature  []byte             `json:"signature"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type EncryptionKey struct {
	ID         int32              `json:"id"`
	PublicKey  string             `json:"public_key"`
	PrivateKey []byte             `json:"private_key"`
	IsActive   pgtype.Bool        `json:"is_active"`
	Purpose    string             `json:"purpose"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type FileRegistry struct {
	ID           int32              `json:"id"`
	UserID       int32              `json:"user_id"`
	FileName     string             `json:"file_name"`
	ObjectKey    pgtype.Text        `json:"object_key"`
	LockStatus   bool               `json:"lock_status"`
	UploadStatus string             `json:"upload_status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
