// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
)

type Querier interface {
	CountEncryptionKeys(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateEmptyFile(ctx context.Context, arg CreateEmptyFileParams) (FileRegistry, error)
	CreateEncryptionKeys(ctx context.Context, arg CreateEncryptionKeysParams) (EncryptionKey, error)
	CreateUsers(ctx context.Context, email string) (User, error)
	DeleteAPIKey(ctx context.Context, credential []byte) error
	DeleteFile(ctx context.Context, id int32) error
	GetAPIKey(ctx context.Context, credential []byte) (GetAPIKeyRow, error)
	GetActiveKeyBasedOnPurpose(ctx context.Context, purpose string) (GetActiveKeyBasedOnPurposeRow, error)
	GetFileByID(ctx context.Context, id int32) (GetFileByIDRow, error)
	GetFileByName(ctx context.Context, arg GetFileByNameParams) (FileRegistry, error)
	GetUsersID(ctx context.Context, email string) (int32, error)
	LockFile(ctx context.Context, arg LockFileParams) (FileRegistry, error)
	UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (FileRegistry, error)
	UpdateFileName(ctx context.Context, arg UpdateFileNameParams) (FileRegistry, error)
	UpdateKeyStatus(ctx context.Context, arg UpdateKeyStatusParams) error
}

var _ Querier = (*Queries)(nil)
