FROM golang:1.23-bookworm AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/backend_service ./backend/cmd/main.go

FROM gcr.io/distroless/base-debian12:latest AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/bin/backend_service /app/bin/backend_service

EXPOSE 9081

USER nonroot:nonroot

ENTRYPOINT ["/app/bin/backend_service"]